### ISSUE TITLE
længdespring alletiders 16-17-årige

### ISSUE THREAD

**Issue by jfraende** [sebastianskejoe/STatletik#100]
Prøv at lave en alletiders liste for 16 årige (Andreas Trajkovski 7.41) , derefter for 17 årige  (benjamin gabrielsen 7.27) og endelig for 16-17-årige - så dannes der ikke en korrekt liste - Benjamin nr. 1 Andreas er ikke med.

Har ikke testet på andre varianter

**Comment by sebastianskejoe** [comment]
Rettet.
