### ISSUE TITLE
D12/13 år 400 g spyd migreres til 500 g spyd

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#105]
Submitter: Jeppe Hansgaard
Email: jeppe.hansgaard@innovisor.com
Hej.
Alle Spydkast 500 Gram resultater lavet af Vitus Lei Hansgaard, Holte Atletik er fejlregistreret. De skulle være registreret som 400 Gram (som er de spyd, der bruges af 12-13 årige drenge).
Glædelig jul.
Jeppe

**Comment by jfraende** [comment]
Hej Jeppe

Det er desværre en migreringsfejl fra den gamle version af Statletik til 
den nye. Resultaterne er rigtig registreret i det gamle system.
Det kommer på listen med fejlrettelser.

## 

Mvh.
Jesper Frænde
Statletik

Den 20-12-2015 kl. 10:40 skrev Sebastian Skejø:

**Comment by sebastianskejoe** [comment]
Rettes ved næste migrering.
