### ISSUE TITLE
Status DMU kvalliste?

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#108]
Submitter: Charlotte Beiter Bomme
Email: charlotte@sparta.dk
Kommer der DMU inde kval.lister på Statletik, som der plejer?

**Comment by jfraende** [comment]
Hej Charlotte

Det håber jeg absolut der gør - Men jeg er afhængig af at Tom eller 
Sebastian får sat det op efter nytår.

## 

Mvh.
Jesper Frænde
Statletik

Den 28-12-2015 kl. 00:48 skrev Sebastian Skejø:

**Comment by jfraende** [comment]
svaret/JF

**Comment by jfraende** [comment]
done
