### ISSUE TITLE
migrering af rekorder der i v2 kun er bedstenotering

### ISSUE THREAD

**Issue by jfraende** [sebastianskejoe/STatletik#113]
Tjek 400 meter inde http://old.statletik.dk/output/pdfrekordinde.php?alder=ung&sex=m 12-15 årige - disse  var tidligere opført som rekord. Men jf. øvelsesoversigten er det ikke rekord - men bedstenotering. Men det ser ikke ud til at resultaterne bliver overerført - se fx http://statletik.dk/index.php/Rankings/index/400m/0/m/indoor/0/14/14/0/1/1/10/0

For at vi har styr på bedstenorteringer er det vigtig de bliver overført.

**Comment by sebastianskejoe** [comment]
Bedstenoteringsresultaterne bliver overført, men det ser ud som at lige præcis Peter Voigts resultat ikke kommer med over (se for eksempel Lars Pedersen resultat for D13: http://statletik.dk/index.php/Rankings/index/400m/0/m/indoor/0/13/13/0/1/0/10/0). Jeg undersøger sagen.

**Comment by sebastianskejoe** [comment]
Peters resultat kommer ikke med over, da datoen er registreret som ++.02.88. Det nye system kan kun overføre, hvis det får en gyldig dato. Kan vi grave datoen for dette resultat frem et sted?

**Comment by jfraende** [comment]
Fandt ud af resultatet er opnået ved DM inde 1988 - det foregik 21/22-02 - jeg ved ikke hvilken dag rekorden er sat, men har valgt at registrere det som den 21/2
