### ISSUE TITLE
rekorder sat i m/k-løb skal markeres

### ISSUE THREAD

**Issue by jfraende** [sebastianskejoe/STatletik#114]
Hvis der sættes rekord i en konkurrence hvor M/K er konkurrerer sammen, så SKAL det jf. bestemmelserne fremgå ved rekorden - se http://old.statletik.dk/output/pdfrekord.php?alder=ung&sex=k under 3000 m og 5000 m. 

Denne rettelse er vigtig

**Comment by sebastianskejoe** [comment]
Dette skal vel også markeres på ranglister?

**Comment by jfraende** [comment]
tja - det burde det vel. I bestemmelserne står det kun eksplicit ved rekorder. Det er nok svært i praksis at se ud af resultatlisterne - så for mig er det nok det kun er ved rekorder.

**Comment by sebastianskejoe** [comment]
Rettes i næste migrering.
