### ISSUE TITLE
migrering af mangekampe

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#115]
Submitter: Anke Hagen
Email: anke@dtu.dk
Under profiler mangler oplysninger om veteraner - veteranpoint. F.eks. hos mig (Anke Hagen) er point for kastefemkamp gjort op med seniortabel, selvom de blev optjent i K45. 
Der mangler desuden 7-kamp resultater for Anke Hagen fra 2012 og 2014 (Helsingør) ... 
I det hele taget mangler der en del veteranresultater/point. Også for andre atleter. Det er enormt synd, fordi statletik jo er den eneste kilde for resultater/rekorder osv. og alle informationer var tilstede i den gamle version.

Hvornår regner I med at have opdateret med alle resultater og rigtige (veteran) point?

Mvh
Anke

**Comment by jfraende** [comment]
Hej Anke

Vi har nogle udfordringer med mangekampe og kastemangekampe på det nye 
statletik - vi arbejder på at løse det inden udesæsonen.

Ind til videre kan mangekampe findes på det gamle statletik 
http://old.statletik.dk/

Her skulle du gerne kunne finde dine resultater, ellers er du velkommen 
til at skrive igen.

## 

Mvh.
Jesper Frænde
Statletik

Den 01-01-2016 kl. 18:29 skrev Sebastian Skejø:

**Comment by jfraende** [comment]
Kære Jesper

Mange tak for dit svar. Jeg håber, at I snart få løst alle problemer. Mit indtryk er også, at veterankastresultater ikke er helt kommet over endnu.

Held og lykke med systemet.

Mvh
Anke

Anke Hagen

Head of Section Applied Electrochemistry, Prof. Dr. rer. nat

DTU Energy

Technical University of Denmark

[http://www.dtu.dk/images/DTU_email_logo_01.gif]

Department of Energy Conversion and Storage

Risø Campus, Frederiksborgvej 399

Building 775

DK-4000 Roskilde

Direct +45 46775884

anke@dtu.dkmailto:anke@risoe.dtu.dk

www.dtu.dkhttp://www.dtu.dk/

**Comment by sebastianskejoe** [comment]
Rettes i næste migrering.
