### ISSUE TITLE
rod i hækrekorder og kasterekorder

### ISSUE THREAD

**Issue by jfraende** [sebastianskejoe/STatletik#118]
tjek 110 m hæk og 400 hæk
http://statletik.dk/index.php/Records/index/male/outdoor/youth

hækhøjder blandes sammen - samme med kastedisciplinerne

**Comment by sebastianskejoe** [comment]
Det skyldes at der er registreret "ekstra" rekorder i det gamle system, hvis et resultat er lavet under sværere betingelser. Fx er D19 kuglestødsrekorden Lasse Larsens 18.27m med 6kg, men Blerim Poliski har stødt 16.67 med en 7.26kg kugle, hvilket også er registreret i det gamle system som en rekord, men i det nye system blot bør være en bedstenotering.

Jeg tænker den rigtige løsning er at fjerne de "forkerte" rekorder fra det gamle system, men jeg ved ikke om de kan have et historisk formål?

**Comment by jfraende** [comment]
Jeg er ikke helt sikker på at jeg forstår det  - Blerims kast er netop indtastet som en bedstenotering - derfor skal det stadtig være registreret på Statletik, men ikke på rekordlisten

http://old.statletik.dk/admin_bedstenotering.php?sex=19&underdisc=&disc=ks_m&button=Find+liste

**Comment by sebastianskejoe** [comment]
Løses næste gang migreringen kører.
