### ISSUE TITLE
forkert rekorder vises + historiske rekorder vises

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#128]
Submitter: Peter Kirkegaard
Email: PETE@hempel.com
Kære Statletik

Der er et par enkelte fejl i registreringen af resultater for Anne Sofie Kirkegaard (1998). 

Hun er tilsyneladende oprettet oprettet med to fejlagtige profiler: 

Anna Sofie Kirkegaard (1998) - Anne og ikke Anna
Anne Sofie Kirkegaard (1996) - Årstallet er 1998 og ikke 1996.

Det betyder, at også rekordlisterne er fejlagtige. 

På forhånd tak og med venlig hilsen

Peter Kirkegaard
Mobil 2120 3225
Email pete@hempel.com

**Comment by jfraende** [comment]
Hej Peter

Jeg kan kun finde én profil på Anne Sofie Kirkegaard - kan du sende et 
link til de fejlagtige profiler.

## 

Mvh.
Jesper Frænde
Statletik

Den 19-01-2016 kl. 17:47 skrev Sebastian Skejø:

**Comment by sebastianskejoe** [comment]
Det ser ud til at det er løst nu. Jeg tror det har skyldtes at migreringen er "død" midt i forløbet og derfor ikke har fået alle rekorder med over, samt ikke har fået opdateret, hvilken rekorder der er aktuelle. Der er ikke rigtigt nogen god måde at løse det på desværre, indtil vi skifter helt over.
