### ISSUE TITLE
jf/tjek rekord

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#136]
Submitter: Kjeld Muff
Email: muff@cool.dk
Greves 18-19 årige hold satte dur inde i Skive til DMU-2015 på 4x200 m. Der var tale om et rent 18 års hold: Asger Østerby, 97, Sebastian Romer, 97, Kenneth Pedersen, 97 og Kasper Andersson, 97. Tiden 1.35,79 sek er ny rekord, idet den gamle var vakant.

Ved samme stævne satte Sparta også ungdomsrekord med et rent 1999 hold i D-16-17 års gruppen med 1.38.59. Tjek selv resultatlisten.

mvh.

Kjeld Muff

**Comment by jfraende** [comment]
Hej Kjeld

Jeg kigger på det en af de nærmeste dage.

## 

Mvh.
Jesper Frænde
Statletik

Den 24-01-2016 kl. 19:45 skrev Sebastian Skejø:

**Comment by jfraende** [comment]
Hej Kjeld

Så har jeg fået kigget på det - der var ikke påført årgang på atleterne 
i resultatlisten, og derfor bliver de automatisk oprettet som tilhørende 
17-årige. Men jeg har nu registreret rekorderne. Tak for hjælpen.

## 

Mvh.
Jesper Frænde
Statletik

Den 24-01-2016 kl. 19:45 skrev Sebastian Skejø:
