### ISSUE TITLE
Migrering af rekorder

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#153]
Submitter: Keyvan Rasmussen
Email: keyvan.rasmussen@gmail.com
Hej STatletik, det ser ud til at alle rekorder fra 2015 og måske også 2016 er forsvundet. Har I nogen tekniske problemer?

Mvh
Keyvan Rasmussen

**Comment by jfraende** [comment]
Hej Keyvan

Vi har pt problemer med at få overført alle rekorder til den nye version 
af Statletik. Vi arbejder på sagen.
Men du kan se alle officielle rekorder her - 
http://old.statletik.dk/rekorder.php

## 

Mvh.
Jesper Frænde
Statletik

Den 14-02-2016 kl. 19:33 skrev Sebastian Skejø:

**Comment by sebastianskejoe** [comment]
Rettet.
