### ISSUE TITLE
Datofejl kuglestød

### ISSUE THREAD

**Issue by jfraende** [sebastianskejoe/STatletik#157]
På alle tiders ranglisten kuglestød 4 kg står Karoline Mangor som nr. 65 med 11.92

65  Karoline Mangor 1998    Sparta AM   11.92   2012-07-07

Det er korrekt - men resultatet er ikke opnået 7/7-12 men derimod 12/9-15.

Det "sjove" er at hun faktisk stødte 11.92 den 7/7-112 - men det var med 3 kg kuglen! Hvilket er korrekt registreret.

**Comment by sebastianskejoe** [comment]
Karoline har i mellemtiden stødt længere, så problemet er der ikke nu, hvilket gør det svært at rette. Jeg lukker dette issue, men har det i baghovedet, hvis vi støder ind i det igen.
