### ISSUE TITLE
Kapgang overføres ikke korrekt

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#158]
Submitter: Aksel V. Bendtsen
Email: avb@postman.dk
Hej 
DM inde kapgang 27. feb. 2016
der har i ikke fået alle resultaterne med
herre veteraner 3000 m mangler
og ungdom 2000 m

venligst 
Aksel V. Bendtsen

**Comment by jfraende** [comment]
Alle disciplinerne bliver ikke overført - se http://old.statletik.dk/event.php?id=4570

**Comment by jfraende** [comment]
rettet
