### ISSUE TITLE
Fejl overførsel af spyd 400g og 500 g ombyttes

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#184]
Submitter: Micahel Skifter Andersen
Email: delta@slagelseatletik.dk
Jeg har opdaget en fejl på statletikken fra stævnet i Slagelse den 23.6 2015.
Her er I kommet til at bytte rundt på de kvindelige spydkastere, så dem der kastede med 400g spyd er skrevet ind med 500g spyd og omvendt.
Det vil sige at I har registreret de 12-13 årige piger med 500g og de 14-15 årige, samt 16-17 årige med 400g spyd.

Med venlig hilsen
Michael Skifter Andersen
Slagelse Atletik DELTA

**Comment by jfraende** [comment]
Hej Michael

Godt set  - det er faktisk registreret korrekt 
http://old.statletik.dk/event.php?id=4117 - men der sker en fejl i 
overførelsen til den nye statletik.
Jeg har sat programmøren på opgaven. Jeg ved ikke hvornår det bliver rettet.

## 

Mvh.
Jesper Frænde
Statletik

Den 28-04-2016 kl. 07:51 skrev Sebastian Skejø:
