### ISSUE TITLE
500 g spyd og højde på forhindringsløb

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#218]
Submitter: Peter Bjerre
Email: fambjerre@stofanet.dk
Til Statletik:
Såfremt det måtte have interesse, følger her nogle ændringer, rettelser og tilføjelser til eksisterende atletikresultater.
Ændringer:  I opsætningen mangler der 500 g spyd, der anvendes af kvinder 50-59 år og mænd 70-79 år. NB: Der ses alene anvendt 600 g 
                   og 400 g spyd.
                   NB: Mine 2.000 m forh`s resultater er sat på 76,2 cm. NB: Ved overgang til 2.000 m forh. for mænd fra 60 år er højden 76,2 cm.

Rettelser:    5-kamp inde 65-69 år 2109p Peter Bjerre 18.12.42 Aarhus 1900 AM. Sat 06.02.11 ved DVM inde i Marselisborghallen, Aarhus.
                   NB: Det var som "Veteran" og ikke som M 17, som står skrevet.

Tilføjelser:  100 m 65-69 år 16,90 +0,5 Peter Bjerre 18.12.42 Aarhus 1900 AM. Sat 22.09.07 i 10-kamp ved AMG Memorial åbne  
                   klubmesterskaber på Odense Atletikstadion.
                   200 m 65-69 år 37,4 Peter Bjerre 18.12.42 Aarhus 1900 AM. Sat 03.06.07 ved Vestdansk M på Sønderborg Stadion.
                   1 mile 65-69 år 6.28.52 Peter Bjerre 18.12.42 Aarhus 1900 AM. Sat 14.08.07 ved ABC-stævne på Aarhus Stadion.
                   300 m hæk(76,2 cm) 65-69 år 63,32 Peter Bjerre 18.12.42 Aarhus 1900 AM. Sat 30.06.07 ved NVM på Aarhus Stadion.
                   2.000 m forh.(76,2 cm) 65-69 år 9.05.19 Peter Bjerre 18.12.42 Aarhus 1900 AM. Sat 30.06.07 ved NVM på Aarhus Stadion.
                   5-kamp inde 70-74 år 2123p Peter Bjerre 18.12.42 Aarhus 1900 AM. Sat 03.02.13 ved VDM inde i Marselisborghallen, Aarhus.

Det var det væsentligste af nyere data set i forhold til Statletik.

Med venlig hilsen
Peter Bjerre.

**Comment by jfraende** [comment]
Hej Peter

Tak for din mail. Se svar med rødt herunder.

Mvh
Jesper Frænde
Statletik

Den 22-06-2016 kl. 14:43 skrev Sebastian Skejø:

**Comment by sebastianskejoe** [comment]
500g spyd for mænd migreres nu. Migreringen har hele tiden fungeret for kvinder.

**Comment by sebastianskejoe** [comment]
Lukker denne da forhindringsløbsproblemet også er dokumenteret i #71.
