### ISSUE TITLE
Rollebaseret login system

### ISSUE THREAD

**Issue by kfroberg** [sebastianskejoe/STatletik#288]
Integration af community-auth (http://community-auth.com) rollebaseret login system

Følgende tasks skal laves.
- [x] Integration af community auth plugin i eksisterende kodebase
- [x] Få community auth - eksempel applikationen op at køre, så der kan logges ind
- [x] Få integreret community-auth sql, så det bliver genindlæst når databasen initieres
- [x] Definition bootstrap rolle og bruger, så der kan logges ind på et blank system.
- [x] Simpel login side
- [x] Dokumentation af hvordan brugere og roller administreres.
- [x] Dokumentation af hvilke sider der skal beskyttes, og hvilke roller der skal have adgang til dem.
- [x] Check op på at php sessions er slået til i driftsmiljøet (database baserede sessions)
- [x] Ryd op i community auth eksempler der ikke skal bruges.

**Comment by kfroberg** [comment]
Rollebaseret loginsystem er nu implementeret
Det bør testes grundigt inden det rulles ud på livemiljø

**Comment by sebastianskejoe** [comment]
Reviewer og tester.

**Comment by sebastianskejoe** [comment]
Første review overstået. Tester videre lokalt.
