### ISSUE TITLE
Marathontid ikke registreret

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#305]
Submitter: Henrik Gehlert
Email: henrikgehlert@gmail.com
Hej,
Hvor lang tid går der inden tiderne fra Berlin Marathon 2016 bliver registreret i systemet?
Jeg husker at Berlin Marathon er AIMS godkendt.

De bedste hilsner
Henrik Gehlert :-)

**Comment by jfraende** [comment]
De er registreret nu.

Mvh

Jesper Frænde

Statletik

Den 25-10-2016 kl. 12:12 skrev Sebastian Skejø:
