### ISSUE TITLE
Vægtkast årsbedst

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#306]
Submitter: Kirsten Eskildsen-Møller
Der står at jeg har kastet 19.53 i vægtkast. 
Resultatet i Aalborg var 10m og et eller andet som samtidig var PR.

**Comment by jfraende** [comment]
Hej Kirsten

Det er det resultat der fremgår af resultatlisten

http://dansk-atletik.dk/resultater/resultatarkiv/2016/10-15-kastestaevne,-aalborg.aspx

Aalborg må lige kigge i dommerlisten og sende en rettelse.

Mvh

Jesper Frænde

Statletik

Den 26-10-2016 kl. 07:09 skrev Sebastian Skejø:
