### ISSUE TITLE
manglende resulat

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#309]
Submitter: René Kvist 
Email: renekvist@youmail.dk
ved regionsfinalen i Kolding d. 100916 sprang Max K, Andersen 2003 Randers Freja 1,65 m i højde , det resultat er ikke kommet med i statletik , kan det komme med :) tak

DRENGE 12-13 ÅR - HØJDESPRING
LØR KL. 14.45  
Nr
Resultat
 
Navn
Klub
Points
 
1
 
1.70
 
ROED Kristian -2003
Østjylland
12p
 
2
 
1.65
 
KØRNER Max -2003
Østjylland
11p
 
3
 
1.45
 
ILSØ Rasmus -2003
Sønderjylland
10p
#  

 
1.45
 
SIGALA Samuel Emil Gobina -2003
Nordvestjylland
10p
 
5
 
1.45
 
SÆKMOSE Hans -2004
Sydjylland
8p
 
6
 
1.40
 
LUND Magnus -2003
Sydjylland
7p
 
7
 
1.40
 
HORN Lasse -2003
Sønderjylland
6p
 
8
 
1.40
 
SØRENSEN David Østergaard -2003
Nordvestjylland
5p
 
9
 
1.30
 
DICHMANN Tobias Skak -2003
Østjylland

**Comment by jfraende** [comment]
Hej Rene

Det skyldes at han til stævnet stillede op under navnet Max Kørner uden 
klubangivelse og derfor ikke er blevet genkendt på Statletik.

Jeg sørger for at knytte resultatet til hans profil.

Som klub vil det være dejligt hvis I tilmelder jeres atleter under det 
navn der er registreret på Statletik.

Mvh

Jesper Frænde

Statletik

Den 30-10-2016 kl. 17:36 skrev Sebastian Skejø:
