### ISSUE TITLE
Rangliste - 2000m

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#31]
Submitter: Michael Christensen
Email: amageratletik@email.dk
Hej Statletik,
kanon med det store arbejde i laver med statikkerne.
Ville lige tjekke hvor præcise de er så tog et eksempel hvor jeg selv har deltaget.
I ranglisten på 2000 m har jeg selv løbet 5.47,4 i 1993 - og er ikke på listen.
Men Victor Thomsen der løb 5.51,53 i 2014 er i listen.
Han vil da ikke anerkende at jeg har klubrekorden når han ikke kan se mit resultatet.
Hvad er kreterier for at komme på listerne ?
Venlig hilsen
Michael Christensen

**Comment by jfraende** [comment]
besvaret/JF
