### ISSUE TITLE
Opdatering af personlige rekorder i Statletik

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#311]
Submitter: Nicolaj R Sørensen
Email: nrs800@hotmail.com
Kære Statletik,

Vil det være muligt at få opdateret mine personlige rekorder (udendørs) under min profil i Statletik? Det er i øjeblikket kun min 800 m tid, der er korrekt opført.

Mine personlige rekorder er følgende:

200 m 23,05 sek. Glostrup 29.05.1999 (DAF i tal 1999 side 230)
300 m 35,85 sek. Hvidovre 07.05.1999 (DAF i tal 1999 side 232)
400 m 48,77 sek. Glostrup 29.05.1999 (DAF i tal 1999 side 234)
1000 m 2.27,17 sek. Holbæk 21.06.2005 (DAF i tal 2005 side 238)
1500 m 3.57,65 sek. Østerbro 06.06.2005 (DAF i tal 2005 side 240)
5000 m 16.00,32 min. Hillerød 27.08.2006 (DAF i tal 2006 side 223)

På forhånd tak.

Med venlig hilsen
Nicolaj R Sørensen
FIF Hillerød Atletik

**Comment by jfraende** [comment]
Kære Nikolaj

Statletik dækker pt. kun data tilbage fra 2008 og for ungdom tilbage fra 
2010. Ældre data optræder kun, såfremt det er, eller har været 
ungdomsrekord eller er på alle tiders top50 senior.

## 

Mvh.
Jesper Frænde
Statletik

Den 01-11-2016 kl. 23:06 skrev Sebastian Skejø:
