### ISSUE TITLE
Statletik profil

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#313]
Submitter: Benjamin Savill
Hej,

Er det muligt at opdater mit profil lidt - der mangler min tider fra Koebenhavn 1/2 Marathon 2016, og Etape Bornholm 2015 og 2016, og min 5k tider fra Storbaelt Naturmarathon 2014 og 2015. Jeg har ogsaa loebet en 10km i England - Eastleigh 10k (20/03/2016) paa 31:48. Du kan se alle mine tider her: http://www.thepowerof10.info/athletes/profile.aspx?athleteid=93937

Med venlig hilsen,
Benjamin Savill

**Comment by jfraende** [comment]
kan ikke besvares pga mail mangler
