### ISSUE TITLE
Skift af klub

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#316]
Submitter: Thomas Dam Lorentzen
Kære Statletik,

Har I mulighed for at rette min klub fra Sparta til Snik Atletik? Den tid jeg løb til Berlin Marathon 2016 var under Snik og ikke Sparta.
Tusind tak for hjælpen. 

Mvh Thomas

**Comment by jfraende** [comment]
Hej Thomas

Det er rettet nu og kan ses imorgen.

## 

Mvh.
Jesper Frænde
Statletik

Den 19-11-2016 kl. 13:46 skrev Sebastian Skejø:
