### ISSUE TITLE
Rapportering om svenske  stævner

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#328]
Submitter: Jesper Lützen
Email: jelut@live.dk
Hvor rapporterer man om resultater fra stævner i Sverige??? - jeres kontakt-ting drejer sig umiddelbart om forbedringer og fejl.

**Comment by jfraende** [comment]
Hej Jesper

Link til resultatliste sendes til resultater@dansk-atletik.dk - læs evt. 
mere her http://dansk-atletik.dk/resultater/om-resultatlister.aspx


-- 
Mvh.
Jesper Frænde
Statletik



Den 12-12-2016 kl. 08:41 skrev Sebastian Skejø:
