### ISSUE TITLE
leder efter gamle indendørs resultater

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#330]
Submitter: regin thomsen
hej

efter sigende er den færøske inderdørs rekord for 60m 7,20 (ási mikkelsen, født i 1973, klub 1900)
men jeg finder ikke noget som kan verifisere de)tte.
på denne liste er han ikke: http://old.statletik.dk/output/pdfseniorinde.php?aar=1997

har ledt i årbogen for 1997 (det er ikke engang sikkert det var i 1997, men mellem 1996 og 2000 må det være.)
fandt ham på en anden disiplin i 1997 årbogen (længdesprint på 7,05 indendørs i forb. med med dm inde i malmø 1-2 marts 1997)
foreløbig har rói holgarson færøsk inde rekord med 7.23....

kan i hjælpe? kan i se noget

mvh
regin thomsen, færøerne

**Comment by jfraende** [comment]
Hej Regin

Håber det er den rigtige mailadresse - du har ikke opgivet den.

Men jeg har fundet dette resultat i en gammel statistikbog

Måske er det det du søger?

-- 
Mvh.
Jesper Frænde
Statletik



Den 25-12-2016 kl. 00:10 skrev Sebastian Skejø:
