### ISSUE TITLE
2 profiler er samme atlet

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#331]
Submitter: Jesper Lønborg
Email: jesperlnborg@yahoo.dk
Hej Statletik,

Nedenstående er samme person, men fik øjensynligt ikke sit mellemnavn med fra Julestævnet.

Mik Resen Lønborg - 2003 - Københavns IF
Mik Lønborg - 2003 - Københavns IF

Har I mulighed for at samle resultaterne på kun en profil?

På forhånd tak:)

Mvh. Jesper Lønborg (Mik's far)

**Comment by jfraende** [comment]
Hej Jesper

Det er rettet nu. Det vil være fint hvis I fremover vil bruge det fulde 
navn ved stævnetilmelding. Det mindsker risikoen for fejl fremover.

-- 
Mvh.
Jesper Frænde
Statletik


Den 29-12-2016 kl. 12:53 skrev Sebastian Skejø:
