### ISSUE TITLE
Længdespring til syævne

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#332]
Submitter: Julie Harsman
Email: julie.harsmann@live.com
Hej. Inde på min statletikprofil (Julie harsman - Aarhus 1900) står der at jeg har sprunget længdespring til et ABC-stævne d. 10/12 2016. Jeg lavede ikke længdespring den dag og derfor må det være en fejl at resultatet er sat ind. Jeg vil derfor venligst bede jer om at slette det. 

Mvh. Julie Harsmann

**Comment by jfraende** [comment]
Det er rettet.


-- 
Mvh.
Jesper Frænde
Statletik

Den 01-01-2017 kl. 12:52 skrev Sebastian Skejø:
