### ISSUE TITLE
Min bedste 10-kamp dog med vind

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#333]
Submitter: Christian Lauge Laugesen
Email: lauge10@hotmail.com
Synes der mangler en del resultater under min primære profil Christian Laugesen. Kan se der er et par enkelte under Christian L. Laugesen. Men min bedste score i en 10-kamp fra 2008 i Arles, dog i medvind, lyder på 7473 point. Den må meget gerne noteres:)

**Comment by jfraende** [comment]
Hej Christian

Dine to profiler er nu samlet.

10-kampresultatet fra 2008 er ikke gyldig i statistisk sammenhæng pga 
for meget vind. Det er først inden for de sidste  par år at vi har haft 
mulighed for er registrere vind-resultater på Statletik. Da vi har mange 
arbejdsopgaver, prioriterer vi ikke at rette det bagud i tiden, da der 
ikke er tale om et godkendt resultat.

-- 
Mvh.
Jesper Frænde
Statletik


Den 03-01-2017 kl. 13:10 skrev Sebastian Skejø:
