### ISSUE TITLE
Kvinder 5 km

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#334]
Submitter: Birgitte Helwigh
Hej med jer

Kvindernes/unge kvinders rekorder på 5 km mangler.

mvh
Birgitte

**Comment by jfraende** [comment]
Hej Birgitte

Det er ikke muligt at sætte ungdomsrekord på 5 km. Det er kun 10 km der 
kan tælle som rekord i landevejsløb for ungdom.

Der kan sættes bedstenotering på distancen - du kan fx finde 
bedstenoteringer for U18 ved at indstille ranglisterne som vist her - 
http://statletik.dk/index.php/Rankings/index/5km/0/f/outdoor/0/12/17/0/1/1/1/10/0

-- 
Mvh.
Jesper Frænde
Formand Projektgruppen Statistik
Dansk Atletik Forbund


PS: Resultaterne fra Änglamarkløbet er ikke endeligt godkendt pga tvivl 
om løbets længde, så de er ikke med på statistikken.


Den 04-01-2017 kl. 14:10 skrev Sebastian Skejø:
