### ISSUE TITLE
Fejl for længdespring

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#335]
Submitter: Benny Machon
For piger, 12 år, længde, inde er der to resultater i alletiders listen der nok er forkerte.
Der er to piger med hhv. 9.48 og 9.50 som resultater.

**Comment by jfraende** [comment]
Tak, det er rettet.


-- 
Mvh.
Jesper Frænde
Statletik

Den 04-01-2017 kl. 15:32 skrev Sebastian Skejø:
