### ISSUE TITLE
Mie Hylling Axelsson - 2002 - tid i Ânglemark Nytårsløb 31-12-2016

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#339]
Submitter: Lars Hylling Axelsson
Email: lars@hyllingaxelsson.dk
Mie Hylling Axelsson - 2002 (Sparta) er registreret med 19:29 som 5 km tid i Ânglemark Nytårsløb 31-12-2016

Den officielle tid er 19:26 - se link http://live.ultimate.dk/desktop/front/index.php?eventid=3048&ignoreuseragent=true

**Comment by jfraende** [comment]
Hej Lars

Til statistik bruger man bruttotider - og her er Mies tid 19.29.


-- 
Mvh.
Jesper Frænde
Statletik

Den 18-01-2017 kl. 10:14 skrev Sebastian Skejø:
