### ISSUE TITLE
Resultat 300 m

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#345]
Submitter: Louis Christiansen
Email: louis.christiansen@skolekom.dk
Hej.
I Dybvad IK har vi en mor, som gerne vil have nedenstående resultat med på ranglisten.

Sidste Chance, Aalborg, 2016-12-27

Jelmer Scholten, 2004, Dybvad IK, 46,38 sek.

Venlig hilsen, Louis

**Comment by jfraende** [comment]
Tak - det er tilføjet nu.

-- 
Mvh.
Jesper Frænde
Statletik

Den 24-01-2017 kl. 12:19 skrev Sebastian Skejø:
