### ISSUE TITLE
old.statletik og DMU kval.liste

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#355]
Submitter: Vandy Nielsen
Email: info@smykkesten.dk
Hej

I nattens mulm og mørke er adgang til old.statletik og DMU kval. liste tilsyneladende
forsvundet?

Er old. statletik lukket helt ned?

Måske er jeg gammeldags men kunne egentlig bedre lide den gamle udgave.

Hilsen
Vandy

**Comment by jfraende** [comment]
Hej Vandy

Kvallisten finder du her - http://statletik.dk/index.php/Lists/view/3

Den gamle statletik side var desværre tung at opdatere og plaget af 
nedbrud og levede ikke op til de sikkerhedskrav ift. data, som er 
nødvendig i 2017. Vi har derfor været nødt til at gentænke hele sitet og 
databasestrukturen forfra.
Det er på plads nu og vi vil fortsætte med at forbedre og udvikle siden.

-- 
Mvh.
Jesper Frænde
Statletik


Den 27-01-2017 kl. 09:20 skrev Sebastian Skejø:
