### ISSUE TITLE
Danske rekorder

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#359]
Submitter: Michael Bruun Jepsen
Hej Jesper & Co
I rekordsektionen mangler der samtlige rekorder i almindelige mangekampe og kastemangekampe.
Hvornår forventer I, at de kommer op?
Fortsæt det gode arbejde :)
Michael

**Comment by jfraende** [comment]
Hej Michael

Efter vi har lukket den gamle side har dette høj prioritet.

Sebastian er CC denne mail - så er jeg sikker på det bliver noteret og 
rekorderne snart kan ses :-)

-- 
Mvh.
Jesper Frænde
Statletik



Den 30-01-2017 kl. 08:41 skrev Sebastian Skejø:
