### ISSUE TITLE
Lars Bach - Højde

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#36]
Submitter: Lars Bach Jensen
Email: labj@di.dk
Hej Statletik,

Selvom det er længe siden kan jeg stadig huske min rekorder. Jeg sprang 2.12 m udendørs i 1987 (til DM) og 2.15 (til en inde landskamp i Stange, Norge) indendørs i 1992. Både på ude og inde ranglisten er mine noteringer altså ikke helt korrekte :). 

Bedste hilsner

Lars

**Comment by jfraende** [comment]
besvaret/JF
