### ISSUE TITLE
Piger 15 60m hæk Pallasspelen

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#360]
Submitter: Michael Bruun Jepsen
Hej
I har desværre glemt de Hvidovrepiger, der løb 60m hæk ved weekendens Pallasspelen hos piger 15 år. Det drejer sig om
7	Kjellman Nörremar Carla -02	Hvidovre Atletik & Motion /DK	10,33
6	Kjellman Nörremark Björk -02	Hvidovre Atletik & Motion /DK	10,27
Da det har indflydelse på kval.listerne til DMU, så må de meget gerne tages med :)

**Comment by jfraende** [comment]
Hej Michael

Resultaterne er nu ikke glemt. De er ikke gyldige i Danmark, da de kun 
løber på 5 hække i Sverige.

-- 
Mvh.
Jesper Frænde
Statletik


Den 30-01-2017 kl. 14:53 skrev Sebastian Skejø:
