### ISSUE TITLE
Amalie Ø. Lange resultater 2016 => Anna Ø. Lange

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#361]
Submitter: Morten Larsen
Email: mortenl@greve-atletik.dk
Hej 

Jeg bemærkede lige, at det er noteret at Amalie Ø. Lange har løbet 800m og 100m hæk til NM Mangekamp i Huddinge sidste år (2016).

Kan I flytte resultaterne til hendes søster Anna Ø. Lange?
(det er Anna der var til NM mangekamp :) og har lavet de andre 5 resultater i mangekampen)

**Comment by jfraende** [comment]
Hej Morten

Godt set - jeg synes dog kun det var 800 meter der var forkert. Det 
resultat er flyttet.

-- 
Mvh.
Jesper

Den 31-01-2017 kl. 13:01 skrev Sebastian Skejø:
