### ISSUE TITLE
Mangler på top 100 maraton mænd har været der tidligere.

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#363]
Submitter: Erling Kristiansen 
Kolding KFUM Atletik & motion løbere::
2,21,43 Jørn Warming (1946)                    1981
2,27,12 Preben Henriksen (1959)              1983
2,29,27 Poul Fremmelev   (1957)               1983
2,31,01 Johnny Klausen                              1992

**Comment by jfraende** [comment]
Hej Erling

Jeg tror du må huske forkert.

Vi har tjekket den gamle database og her fremgår resultaterne ikke.

Desuden var de heller ikke blandt de resultater som vi i sin tid lagde 
ind til alle tiders ranglisterne.

-- 
Mvh.
Jesper Frænde
Statletik


Den 01-02-2017 kl. 11:47 skrev Sebastian Skejø:
