### ISSUE TITLE
Opdatering af Profil

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#368]
Submitter: Peter Voigt
Email: pev@credocom.dk
Hej Sebastian

Er der mulighed for at jeg kan få opdateret min Profil med de resultater jeg har kunne finde i årbøgerne.
+ er der hvor jeg mener jeg har lavet bedre resultater men ikke lige kan finde dem, da jeg ikke har været i Top50 det år.

Peter Voigt 1974 Herlev/TIF				
				
100	10.48	28.05.95	Hvidovre	Top-12
200	21.25	04.05.95	Frederiksberg	Kunstoft stævne
300	33.7	26.04.95	Rudegård/Holte	Kunstoft stævne
400	47.52	23.06.95	Østerbro	Top-12
800	2.00.99	xx.xx.92	Herlev		DMU ?
1500	4.36.x ?				DMU 10-kamp
200h	26.23	01.09.93	Herlev	
400h	57.60	24.08.93	Lyngby		DT
4x100	40.09	28.06.96	Bergen		Landsholdet
4x400	3.09.59	29.06.96	Bergen		Landsholdet
60i	6.85	04.03.95	Malmø		DM
200i	21.41	02.03.96	Malmø		DM
400i	49.49	19.02.93	Malmø		DM
1000i	2.47.4	06.02.93	Århus		DMU 7-kamp
4x200i	1.26.50	25.02.96	Göteborg	Landsholdet
Længde	6.96	27.02.94	Århus		DMU
Højde	2.05	01.08.92	Huddinge	NM 10-kamp
Kugle	11.97+	05.06.01	Hillerød	SKAF 5-kamp
Diskos	40.40	14.07.97	Lyngby		DT
Spyd	52.02+	11.06.99	Lyngby		DT ?
Hammer	40.28	05.06.01	Hillerød	SKAF 5-kamp
Vægt	14.37	05.06.01	Hillerød	SKAF 5-kamp
K5-kamp	3178	05.06.01	Hillerød	SKAF 5-kamp

På forhånd tak
Peter

**Comment by jfraende** [comment]
Hej Peter

Tak for din mail.

Statletik består af data data fra 2008 og frem. Derudover har vi data 
der giver valide alletiders lister (top 50/100). Desuden er der rekorddata.

Vi har pt. ikke ressourcer til at lægge yderlige resultater ind. Men det 
er et mål stille og roligt at få mere historisk data ind på statletik. 
Men jeg kan ikke sige noget om hvornår det sker.

-- 
Mvh.
Jesper Frænde
Statletik

Den 05-02-2017 kl. 21:40 skrev Sebastian Skejø:

**Comment by jfraende** [comment]
Hej Jesper

Undre mig bare over at der fx så står en 400m inde fra da jeg var 14 år og ikke den danske senior rekord jeg satte senere… Men den står selvfølgelig heller ikke på ranglisten over 400m inde.
1993 400 m. inde Malmø 19.02.03 49.49. Burde ligge nr. 18, men den er der ikke.

Hvis i skal bruge hjælp med at ligge data inde i databasen må i jo sige til, jeg hjælper gerne.

Med venlig hilsen,

Peter Voigt
Konsulent

Mobil: +45 50 50 19 71 <tel:>
