### ISSUE TITLE
manglende stangsringsresultat

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#369]
Submitter: Maria Suurballe
Email: maria@kakkkelak.dk
Sebastian R. Suurballe (2002) sprang 2.90 til DM Mangekamp i Aalborg 4.2.17, men det resultat kan man ikke se nogen steder på Statletik (heller ikke i kvallisten til DMU). Hans andre resultater fra DM Mangekamp er opdaterede.

**Comment by jfraende** [comment]
Tak - det er rettet.

-- 
Mvh.
Jesper Frænde
Statletik

Den 05-02-2017 kl. 23:16 skrev Sebastian Skejø:
