### ISSUE TITLE
Dagmar Fæster Olsen

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#371]
Submitter: Jesper Borrisholt
Email: jesper.borrisholt@gmail.com
Hej
Jeg har skrevet det til jer tidligere - Dagmar Fæster Olsen har nogle resultater hvor der står "Ballerup AK". Hun har kun stillet op for Allerød AM og Sparta og aldrig Ballerup AK. Vil I rettet dette for en god ordens skyld :-)

På forhånd tak.

Mvh. Jesper, Allerød AM

**Comment by jfraende** [comment]
Hej Jesper

Det skulle være rettet nu.

-- 
Mvh.
Jesper Frænde
Statletik

Den 08-02-2017 kl. 08:59 skrev Sebastian Skejø:
