### ISSUE TITLE
Forkert fødselsår vedr. Zacharias Albert Gustafsen - Helsingør IF - Atletik

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#373]
Submitter: Claus Hansen
Email: chans@gribskov.dk
Zacharias er forkert registreret i Statletik som årgang 2003. Han er født i 2004.

M.v.h.

Claus Hansen
Ungdomstræner
HIF - Atletik

**Comment by jfraende** [comment]
Det er rettet.

-- 
Mvh.
Jesper Frænde
Statletik

Den 13-02-2017 kl. 10:12 skrev Sebastian Skejø:
