### ISSUE TITLE
Forkert resultat 

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#374]
Submitter: Katja Salivaara
Email: katja.salivaara@gmail.com
Hej

I lørdags deltog en af mine atleter, Mathilde Juel Gertz (2002), i længdespring ved Atleticum Spelen i Malmö. Hun fik noteret 4.74 som resultat for hendes første spring, som dog ikke er korrekt. I virkeligheden har hun nok sprunget 3.74. Fejlen blev dog først opdaget efter tredje runde, hvor hun totalt uventet avancerede sig til finalen. Dommerne blev gjort opmærksom på fejlagtig resultat, men jeg kan se at de alligevel har valgt at lade resultatet stå.    

Jeg er i dialog med arrangørerne for at få dem til at ændre/slette resultatet, men jeg håber det kan blive gjort i Statletik allerede inden jeg får et svar fra Sverige, for den har betydning for kvalificering til DMU. 

Med venlig hilsen
Katja Salivaara

**Comment by jfraende** [comment]
Hej Katja

Det er rettet til 4.21 som er Mathildes næstlængste spring.

Men skriv gerne når resultatlisten er opdateret.


-- 
Mvh.
Jesper Frænde
Statletik


Den 13-02-2017 kl. 16:21 skrev Sebastian Skejø:
