### ISSUE TITLE
DM inde 2017 resultat på 4x200m 

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#377]
Submitter: Morten Larsen
Email: mortenl@greve-atletik.dk
Hej
Jeg kan se at I allerede har fået resultaterne ind fra DM inde her i weekenden, selv de sidste stafetter. Godt arbejde!
Jeg undre mig dog over, at vores (Greve Atletik) ikke fremgår vores hold blev nr 2 i andet herre heat og fik bronze i tiden 1.30,19.
Resultater ser samtidig ud til at være D20 samt U23 rekord.

**Comment by jfraende** [comment]
Hej Morten

Det manglende stafetresultat fra Greve skyldes, at jeg pt. ikke kan 
oprette det på Statletik, da det er første gang I stiller et D20 
stafethold.

Programmøren er på sagen, så jeg håber inden for få dage, at resultatet 
er online sammen med rekorden.

PS: Husk U23-rekorden skal anmeldes.


-- 
Mvh.
Jesper Frænde
Statletik


Den 20-02-2017 kl. 00:58 skrev Sebastian Skejø:
