### ISSUE TITLE
Festus Asante´s alder

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#379]
Submitter: Peter  Helge Svendsen
Dette står i Skives resultatstatistik:
Festus Asante skiftede som 19-årig fødselsår fra 1991 til 1994. Dvs at han gik fra være 16 år til 13-årig? Hvilket er i overensstemmelse med hans pas.

Hans resultater passer ikke i forhold til de der står i Skives statistik. Der har han ikke præsteret disse meget meget flotte resultater.

mvh
Peter

**Comment by jfraende** [comment]
Hej Peter

Festus fik som Skive påpeger rettet fødselsår fra 1991 til 1994 for 
nogle år siden.

Hans resultater skal derfor føres under denne årgang - er der nogle der 
er registreret forkert på Statletik?

-- 
Mvh.
Jesper Frænde
Statletik



Den 25-02-2017 kl. 08:21 skrev Sebastian Skejø:
