### ISSUE TITLE
Indendørs alletiders  mænd 800 m 

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#383]
Submitter: Klaus nord andersen 
Email: k.nord60@gmail.com
Hi jeg klaus nord andersen blev dansk mester inde 1987 i tiden 1.50.81 den står ikke på ...min udendørs på 1.50.69 er registreret😊  Hilsen klaus nord andersen

**Comment by jfraende** [comment]
Hej Klaus

Jeg kigger lige nærmere på det.

-- 
Mvh.
Jesper Frænde
Statletik


Den 05-03-2017 kl. 01:05 skrev Sebastian Skejø:

**Comment by jfraende** [comment]
Hej igen

Din indetid var 1.56.81 og ikke 1.50.81.

Dvs. tiden ikke falder ind under de resultater vi pt. har registreret på 
Statletik. Du kan læse om hvilke tider der er registreret her 
http://statletik.dk/index.php/Welcome/faq

-- 
Mvh.
Jesper Frænde
Statletik


Den 05-03-2017 kl. 21:50 skrev Jesper Frænde:
