### ISSUE TITLE
Danske Rekorder inde 60m hæk under 16år

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#384]
Submitter: Morten Larsen
Email: mortenl@greve-atletik.dk
Hej 
Jeg bemærkede i år, da jeg var til Pallas Spelen i Malmö, at P15 60m hæk 76,2cm kun har 5 hække i Sverige, mens man i Danmark har 6 hække. Det ser ud til at I er obs på det nu - da årets hæk resultater fra Pallas ikke optræder på Statletik.

Jeg ved ikke om der altid har været forskel mht antal hække (i Danmark og Sverige) eller det er noget nyt. Men måske har I kontakt til nogle der kan undersøge det?
Jeg er ret sikker på, at Louise Biede stadig har rekorderne (P13 og P14 60H), for hun var i særklasse hurtigere end sine jævnaldrene, men måske skal der findes nogle resultater fra danske stævner, og ikke de 2 fra Göteborg. Jeg siger 'måske', for jeg ved som sagt ikke om antallet af hække var 6 i hhv 2006 og 2007 i Sverige :)

Med venlig hilsen
Morten

**Comment by jfraende** [comment]
Hej Morten

Sverige ændrede hækhøjden for piger 12 og 13 år i 2014. Så hendes p13 
rekord er OK.

Mht hendes p14 rekord er jeg ret sikker på, at du har en pointe. Mig 
bekendt har de hele tiden løbet på 5 hække i modsætning til 6 hække i DK.

Men den optræder også i DAF i Tal 2008 som ungdomsrekord og har 
overlevet siden da

Jeg undersøger det nærmere - hvis det viser sig at de også i 2007 løb på 
5 hække, så bevarer hun dog rekorden, da jeg har dette resultat i mit 
"arkiv"

8,96 	Louise Birch Biede 93 	Silkeborg AK 77 	Århus 	21.01.07


PS: Mht Svenske resultater på Statletik følger vi denne liste - 
http://dansk-atletik.dk/media/434811/Ikke-gyldige-resultater-opnaaet-i-Sverige.pdf
-- 
Mvh.
Jesper Frænde
Statletik


Den 05-03-2017 kl. 01:24 skrev Sebastian Skejø:
