### ISSUE TITLE
Danske Ungdomsrekorder

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#386]
Submitter: Michael Andersen
Hej Jeg kan se, at i har opdateret nogle af ungdomsrekorderne fra DMU i Skive, men der mangler en.

P14 trespring her sprang Josefine Skifter Andersen 2003 Slagelse Atletik DELTA 11,34 meter.

Så mangler der både inde og ude rekorderne i trespring for piger 12-13 år fra Zone, som tidligere har være på listen.

Inde 
P 12 Josefine Skifter Andersen 2003 Slagelse Atletik DELTA 11,24 meter Hvidovre 14/2 2015
P 13 Nickoline Skifter Andersen 1998 Slagelse Atletik DELTA 11,30 meter Århus 27/12 2011

Ude
P 12 Josefine Skifter Andersen 2003 Slagelse Atletik DELTA 11,00 meter Greve 26/9 2015
P 13 Nickoline Skifter Andersen 1998 Slagelse Atletik DELTA 11,27 meter Greve 24/9 2011

Med venlig hilsen
Michael S. Andersen

**Comment by jfraende** [comment]
Hej Michael

Godt du skrev - den havde jeg i første omgang overset. Men er nu tilføjet.

Trespring er ikke officiel disciplin for 12-13-årige jf. 
http://dansk-atletik.dk/media/1485890/fm-afsnit-12-boerne-og-ungdomsbestemmelser.pdf

Derfor er der ikke tale om ungdomsrekord, men derimod bedstenotering. Se 
evt. her - http://statletik.dk/index.php/Welcome/faq hvordan 
bedstenoteringer ses på Statletik.

De stod ganske rigtig på rekordsiden i det gamle Statletik, men det har 
vi forsøgt at rydde op i på den nye version.

-- 
Mvh.
Jesper Frænde
Statletik


Den 06-03-2017 kl. 09:48 skrev Sebastian Skejø:
