### ISSUE TITLE
2 profiler på samme person

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#389]
Submitter: Casper Urth Nygaard
Email: nygaard129@gmail.com
Jeg har åbenbart 2 profiler på mig. En der hedder Casper Nygaard og en der hedder Casper Urth Nygaard og vil høre om de ikke bare kan blive slået sammen

**Comment by jfraende** [comment]
Det er rettet.

-- 
Mvh.
Jesper Frænde
Statletik

Den 17-03-2017 kl. 10:12 skrev Sebastian Skejø:
