### ISSUE TITLE
Rettelse af resultat

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#391]
Submitter: Filippa Dons
Email: statletik@post.dons.dk
Hej Statletik

I har fået noteret det næstbedste resultat for Filippa Dons (P13) i længdespring ved Kronborg Games 3 den 11. marts 2017 (se http://lifeonmars.dk/2017/03-11-kronborg-games/resultatliste_p13.htm).

Hun står noteret for 3,32 på den officielle resultatliste, men 3,10 hos statletik.dk. Det må I meget gerne rette.

På forhånd tak

**Comment by jfraende** [comment]
Tak - det er rettet.

-- 
Mvh.
Jesper Frænde
Statletik


Den 19-03-2017 kl. 08:06 skrev Sebastian Skejø:
