### ISSUE TITLE
att. Jesper Frænde - NBRO/Sparta løbere flyttes til NBRO NRC

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#392]
Submitter: Jacob Larsen - NBRO NRC
Email: nbronrc@gmail.com
Hej Jesper.
Jeg skriver til dig, da vi har oprettet klubben NBRO NRC som er medlem af DAF. Tidligere løb vi under NBRO/Sparta, men da det pludselig skabte udfordringer, har vi oprettet vores egen klub, som i realiteten er den samme, som blot er 100% selvstændig nu.
Jeg har nu 5 løbere, som skal gerne vil løbe DM 10 km. Udfordringen er, at de efter 15. okt. 2016 har løbet cross under NBRO/Sparta. Henrik Paulsen, sportschef for Sparta fortæller mig, at han ikke længere kan tilmelde løbere under NRBO/Sparta, da denne klub ikke eksisterer nu. Dorte fra DAF og Henrik fra Sparta foreslå derfor, at vi flytter disse løbere, som har løbet for NBRO/Sparta efter 15. okt. over til den nye klub NBRO NRC (som egentlig er den samme klub).
Jeg vil defor høre, om du kan flytte disse løbere?
Jeg håber, at vi kan handle hurtigt, da jeg skal have 5 af løberne tilmeldt til DM 10 km i denne uge.
På forhånd tusind tak for hjælpen'
Mvh Jacob Wæver Larsen, NBRO NRC

**Comment by jfraende** [comment]
Hej Jacob

Jeg vil gerne kigge på det i aften, men jeg er nødt til at kende de fem 
navne (og årgang).

Mig bekendt blev I først medlem af DAF 1. januar - er det ikke korrekt?

Hvis det er tilfældet, kan jeg kun rette til NBRO efter 1/1.

-- 
Mvh.
Jesper Frænde
Statletik

Den 20-03-2017 kl. 12:27 skrev Sebastian Skejø:

**Comment by jfraende** [comment]
Hej Jesper,

NBRO National blev medlem på dispensation fra 1. oktober og løb også som sådan til HCA Maraton d. 1. oktober. Vi afventer stadig medlemskab af DIF, men de er medlem af DAF.

Med venlig hilsen
Dorte Ramlov
Sekretær
Dansk Atletik Forbund

[cid:image002.png@01D110C4.A01BDCB0]


dorte@dansk-atletik.dk<mailto:dorte@dansk-atletik.dk> / tlf. 4326 2307
Idrættens Hus, Brøndby Stadion 20, DK-2605 Brøndby
www.dansk-atletik.dk<http://www.dansk-atletik.dk/> www.bevaegdigforlivet.dk/loeb<http://www.bevaegdigforlivet.dk/loeb>

Fra: Jesper Frænde [mailto:jesper@jega.dk]
Sendt: 20. marts 2017 12:34
Til: reply@reply.github.com; nbronrc@gmail.com
Cc: Dorte Maria Ramlov <dorte@dansk-atletik.dk>
Emne: Re: [sebastianskejoe/STatletik] att. Jesper Frænde - NBRO/Sparta løbere flyttes til NBRO NRC (#392)


Hej Jacob

Jeg vil gerne kigge på det i aften, men jeg er nødt til at kende de fem navne (og årgang).

Mig bekendt blev I først medlem af DAF 1. januar - er det ikke korrekt?

Hvis det er tilfældet, kan jeg kun rette til NBRO efter 1/1.
--
Mvh.
Jesper Frænde
Statletik
Den 20-03-2017 kl. 12:27 skrev Sebastian Skejø:

Submitter: Jacob Larsen - NBRO NRC
Email: nbronrc@gmail.com<mailto:nbronrc@gmail.com>
Hej Jesper.
Jeg skriver til dig, da vi har oprettet klubben NBRO NRC som er medlem af DAF. Tidligere løb vi under NBRO/Sparta, men da det pludselig skabte udfordringer, har vi oprettet vores egen klub, som i realiteten er den samme, som blot er 100% selvstændig nu.
Jeg har nu 5 løbere, som skal gerne vil løbe DM 10 km. Udfordringen er, at de efter 15. okt. 2016 har løbet cross under NBRO/Sparta. Henrik Paulsen, sportschef for Sparta fortæller mig, at han ikke længere kan tilmelde løbere under NRBO/Sparta, da denne klub ikke eksisterer nu. Dorte fra DAF og Henrik fra Sparta foreslå derfor, at vi flytter disse løbere, som har løbet for NBRO/Sparta efter 15. okt. over til den nye klub NBRO NRC (som egentlig er den samme klub).
Jeg vil defor høre, om du kan flytte disse løbere?
Jeg håber, at vi kan handle hurtigt, da jeg skal have 5 af løberne tilmeldt til DM 10 km i denne uge.
På forhånd tusind tak for hjælpen'
Mvh Jacob Wæver Larsen, NBRO NRC

**Comment by jfraende** [comment]
Hej Jesper.

Det drejer sig om nedenstående:

Anton Krogsgaard-Jensen, 1989
Anders Rømer, 1983
Rasmus Krodal, 1989
Asmund Biesbjerg Jensen, 1994
Peter Uldall Torp, 1996

Tusind tak for hjælpen.

Mvh. Jacob Larsen, NBRO NRC

Den 20. marts 2017 kl. 12.58 skrev Dorte Maria Ramlov <
dorte@dansk-atletik.dk>:

**Comment by jfraende** [comment]
Hej Jacob

Jeg har kigget på atleterne.

Statletik har fået oplysningerne fra DAF om NBRO's eksistens den 22/12 
og har siden da registreret under denne klub.

Det ser ud til at alle atleter er registreret som NBRO i 2017. Dog ikke 
Rasmus, men det skyldes, han ikke har deltaget i nogen løb. Men jeg har 
skiftet klub på ham.

Er alt så som det skal være?


-- 
Mvh.
Jesper Frænde
Statletik



Den 20-03-2017 kl. 13:35 skrev NBRO NRC:

**Comment by jfraende** [comment]
Hej Jesper

Det lyder helt perfekt.
Tusind tak for hjælpen.

Mvh Jacob

man. 20. mar. 2017 kl. 21.33 skrev Jesper Frænde <jesper@jega.dk>:
