### ISSUE TITLE
Manglende DM 10 km tid

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#393]
Submitter: Christian Reumert Hedetoft
Email: christian.hedetoft@gmail.com
Hej Statletik

Jeg er en relativt nyligt startet atlet, der til daglig løber i AGF Atletik. Jeg skriver til jer, da jeg netop har deltaget i DM 10 km, og ikke kan se min tid herinde. Jeg kan se på nogle af de hurtige gutter, at deres tider fra stævnet er registreret, så jeg gik på opdagelse og fandt frem til reglen om at man skal have en tid (som mand) hurtigere end 35:00 min. før i overfører den her til siden. Jeg bruger Statletik.dk til at gemme mine resultater, så jeg kan få et billede af min udvikling. Selvom min tid på 36:00 min. altså ikke er hurtig nok til at blive overført hertil, så håbede jeg at i måske alligevel kunne lokkes til at overføre denne, ligesom i overfører resultater fra udenlandske stævner, da det vil være rigtig fedt at du følge med i hvordan udviklingen kommer til at gå.

På forhånd tak :-)

Dbh.
Christian Reumert Hedetoft

**Comment by jfraende** [comment]
Hej Christian

Tak for din mail.

Vi kan desværre ikke gøre undtagelser på dette område. Du må løbe en 
anelse hurtigere, så vi kan registrere din tid ;-)

-- 
Mvh.
Jesper Frænde
Statletik


Den 14-04-2017 kl. 14:52 skrev Sebastian Skejø:
