### ISSUE TITLE
profiller

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#394]
Submitter: Esbeen Elbaek
Email: ee@aalborg-roadrunners.dk
Jeg kan se at Maja Boe mangler sin Marathon i sin profil

3.08.26 Maja Boe '60,Aalborg RRC 21.05  København 

og så forstår jeg ikke lige at Camilla Abel nu Camilla Abel Lindholm kun er noteret for en halvmarathon?

**Comment by jfraende** [comment]
Hej Esbeen

Du kan læse her om hvilke resultater der findes på Statletik - 
http://statletik.dk/index.php/Welcome/faq

Maja resultat er så vidt jeg kan se fra 2006 og dermed fra før 
Statletiks tid. Mht Camillas manglende resultater, må de meget gerne 
sende link til dem du mener der mangler.

-- 
Mvh.
Jesper Frænde
Statletik


Den 16-04-2017 kl. 16:12 skrev Sebastian Skejø:
