### ISSUE TITLE
DMU 2016

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#399]
Submitter: Anton Mjöbäck
Email: mjobackanton@gmail.com
Til sidste DMU ude blev jeg nummer tre, på 400m og jeg ville blive meget glad hvis det kunne stå på statletik. Jeg ved at det ikke kun er mit resultat der mangler fra sidste år, da mange af mine venner har det ligesom mig, så ville også bare lige informere jer om det :)

**Comment by jfraende** [comment]
Hej Anton

Dit 400 m resultat fra DMU 2016 er på Statletik

http://statletik.dk/index.php/Meets/index/4791

-- 
Mvh.
Jesper Frænde
Statletik


Den 08-05-2017 kl. 11:33 skrev Sebastian Skejø:
