### ISSUE TITLE
Para atletik resultater

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#402]
Submitter: Søren Thystrup
Email: sdthystrup@gmail.com
Hej. 

Det kan godt hænde at jeg henvender mig det forkerte sted men skal jo starte et sted... 

Jeg er på jagt efter resultater/rekorder/dokumentation fra para atleter. Er det noget i har eller evt. ved hvor jeg kan finde.
Helt præcist søger Henrik Thomsen fra Haderslev-if's resultater på forskellige distancer. 
Jeg kan finde hans resultater fra Para-ol de 3 gange han har deltaget men det er personlige rekorder jeg søger.

Håber meget i kan hjælpe mig.

Mvh
Søren Thystrup (Haderslev-if)

**Comment by jfraende** [comment]
Hej Særen

Tak for din mail.

Jeg kan desværre ikke hjælpe dig her. VI registrerer paraatleter der er 
medlem af en DAF-klub og som deltager i et stævner på lige fod med 
ikke-para-atleter.

Jeg ved ikke hvor du kan henvende dig - men måske Dansk Idræts Forbund 
kan oplyse det.

-- 
Mvh.
Jesper Frænde
Statletik

Den 10-05-2017 kl. 12:37 skrev Sebastian Skejø:
