### ISSUE TITLE
Resultat fra indisk mesterskab

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#404]
Submitter: Jean Johnsen
Email: Geniusnh4@gmail.com
Hej,

Jeg deltog tilbage i Januar i et mesterskab i indien, dette resultat kunne jeg godt tænke mig på statletik.
Skal jeg sende resultatlisten? 

- Jean

**Comment by jfraende** [comment]
Hej Jean

Hvis der er tale om et stævne afholdt efter IAAF's regler og du er 
medlem af en dansk klub, så er det muligt at få resultatet registreret.

-- 
Mvh.
Jesper Frænde
Statletik


Den 13-05-2017 kl. 20:43 skrev Sebastian Skejø:
