### ISSUE TITLE
Danskere i udenlandske klubber

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#405]
Submitter: Lars Nielsen
Email: larsnielsen@mymacmail.com
Hvordan skal danskere der udover deres egen klub også stiller op for en udenlandsk klub, forholde sig for at få deres resultater på statletik ? Er det nok at gøre opmærksom på dette eller skal der indsendes en resultat liste mm..
Mvh Lars Nielsen

Janne Nielsen (93) 1900 har den 7 maj sprunget 13.12 meter i trespring i Frankrig.
Resultatet fremgår af det europæiske forbunds hjemmeside.

**Comment by jfraende** [comment]
Hej Lars

Jeg har brug for et link til den officielle resultatliste (og ikke til 
ranglister), samt oplysning om land, sted og dato for stævnet.

Det skal sendes til resultater@dansk-atletik.dk så sørger jeg for det 
kommer på Statletik.

Læs evt. mere her http://statletik.dk/index.php/Welcome/faq

-- 
Mvh.
Jesper Frænde
Statletik


Den 14-05-2017 kl. 07:34 skrev Sebastian Skejø:
