### ISSUE TITLE
Manglende resultater - Indestævne den 25 APRIL 2017 i Randers Atletikhal.

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#406]
Submitter: Ralf Tilsted Søndergaard
Email: ralf@remstrup.dk
Hej Statletik
Min datter Liv Tilsted Selmer / Årgang 2004 / Silkeborg / SAK77 - deltog ved inde stævne den 25 APRIL i Randers.

Hendes resultater fra dette stævne er ikke at se på statletik.dk

Med venlig hilsen

Ralf Tilsted Søndergaard
Remstrupvej 26
DK-8600 Silkeborg
ralf@remstrup.dk
20 71 01 61

**Comment by jfraende** [comment]
Hej Ralf

Stævnet blev desværre ikke godkendt af terminsudvalget pga. det ikke er 
blevet anmeldt rettidigt til DAF.

Dermed er resultaterne ikke gyldige til den officielle statistik.

-- 
Mvh.
Jesper Frænde
Statletik


Den 15-05-2017 kl. 20:56 skrev Sebastian Skejø:
