### ISSUE TITLE
Korrektion rangliste indendørs 3000 m mænd

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#407]
Submitter: Mads Tudvad Jensen
Email: tudvad@hotmail.com
På alle tiders rangliste figurerer Kenneth Andreasen som nr 9 med tiden 8:09,39 min. Fint nok. Men nr 2 og 3 i løbet (som var DM inde i Rødovre-hallen i 1985) var Thomas Sørensen og undertegnede, Mads Tudvad Jensen, som løb 8:11,02 hhv 8:13,92. Disse tider mangler på ranglisten.

**Comment by jfraende** [comment]
Hej Mads

På inderanglisterne er det kun top10 der er valid. Derfor falder jeres 
resultater pt. ikke ind under dem der er registreret. Men vi håber at 
kunne udvide listerme. Men det vil ske samlet og systematisk.

Du kan læse mere om Alletiders listerne her - 
http://statletik.dk/index.php/Welcome/faq

-- 
Mvh.
Jesper Frænde
Statletik

Den 17-05-2017 kl. 21:46 skrev Sebastian Skejø:
