### ISSUE TITLE
kan ikke finde atlet længere

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#409]
Submitter: Morten Bank
Til rette vedkommende

jeg søger at finde Malte Bank/Malte Bank-Mikkelsen årgang 2003 fra Sparta, men kan ikke længere finde ham på jeres site, selvom han tidligere har været der

ser frem til at høre fra jer

mvh

Morten Bank
Maltes far

**Comment by jfraende** [comment]
Hej Morten

Du finder din søn her http://statletik.dk/index.php/Profile/index/6063

-- 
Mvh.
Jesper Frænde
Statletik


Den 20-05-2017 kl. 08:44 skrev Sebastian Skejø:
