### ISSUE TITLE
Manglende tid fra DM 10.000m 2017.

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#412]
Submitter: Leslie Olivier
Email: leslie.olivier@gmail.com
Hej,

Der var en stavefejl i mit efternavn  til DM 10.000m 2017 (OLIVER istedet for OLIVIER), så det ser ud til at min tid ikke er blevet registreret på statletik. Som det ses på resultatlisten løb jeg 33:32,79 ((http://dansk-atletik.dk/media/1619399/results-nordic-and-danish-10000m-championship-2017.pdf)

På forhånd tak :)

mvh. 
Leslie Olivier

**Comment by jfraende** [comment]
Hej Leslie

Du er tilføjet nu.

-- 
Mvh.
Jesper Frænde
Statletik

Den 23-05-2017 kl. 13:48 skrev Sebastian Skejø:
