### ISSUE TITLE
Fejl i indtastningen  af resultater fra spyd-kvinder fra DT- Elitedivisionsmatch i Odensen 21. maj 2017

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#413]
Submitter: Knud Andersen
Email: knudandersen@xsmail.com
Til rette vedkommende

Det ser ud til at der sket en fejlindtastning af resultaterne fra kvindernes spydkast i DT elitedivisionsmatchen d. 21. maj 2017 i Odense:
http://statletik.dk/index.php/Meets/index/5179

Umiddelbart ser det ud til, at det er resultaterne fra konkurrencens 2. forsøgsrunde, som er blevet indtastet som det endelige resultat for deltagerne.
Link til den officielle resultatliste: http://imars.dk/liveboard/Events?meetId=05c0cfee-d46e-4b30-8887-fb38444acd7c&dayNo=0&sortBy=2

Mvh Knud Andersen

... og tak for et iøvrigt flot arbejde med Statletik

**Comment by jfraende** [comment]
Hej Knud

Mange tak - det er rettet.


-- 
Mvh.
Jesper Frænde
Statletik

Den 23-05-2017 kl. 15:00 skrev Sebastian Skejø:
