### ISSUE TITLE
To navne

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#414]
Submitter: Rikke Ulslev Degn
Email: rikkepedersen@yahoo.com
Hej,
Jeg optræder på min gamle profil "Rikke Pedersen" (Trongården). Kan i rette denne til "Rikke Ulslev Pedersen", som er det navn, jeg brugte?
Endvidere er jeg startet op igen med noget veteranløb (igår), og i må også meget gerne koble min nye "profil" "Rikke Ulslev Degn" (Ballerup Atletik) til den gamle.
På forhånd tak.
Venlig hilsen
Rikke

**Comment by jfraende** [comment]
Hej Rikke

Alle resultater er nu samlet under Rikke Ulslev Degn.

-- 
Mvh.
Jesper Frænde
Statletik


Den 24-05-2017 kl. 11:39 skrev Sebastian Skejø:
