### ISSUE TITLE
Forkert resultatliste 12/5-17 kastefemkamp

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#416]
Submitter: Rene Nybo
Email: fredericia2405@gmail.com
Der er byttet om på hammerkast for Allan Nielsen og undertegnede. Det skal noteres:
Allan Nielsen 33.37m
Rene Nybo 37.17m

Point for Rene Nybo er 3490p og ikke 3487p

Jeg har givet besked til OGF om fejlene.

Vil I rette det, på forhånd tak! 
Mvh. Rene Nybo, Sparta.

**Comment by jfraende** [comment]
Hej Buster

Vil du bekræfte disse ændringer - de fremgår ikke af den rettede liste 
du sendte forleden.

Og gerne sende korrekt resultatliste.

-- 
Mvh.
Jesper Frænde
Statletik

Den 28-05-2017 kl. 10:25 skrev Sebastian Skejø:
