### ISSUE TITLE
Alletiders ranglister mænd

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#418]
Submitter: Jens Pedersen
Email: jensp742@hotmail.com
Rettelser/ændringer 110 m hæk:                                                                                                               
Jørgen Bjarne Nielsen, 18-03-1916, Ben Hur, 15.0, 11-08-1940, Østerbro. Kilde:Sven Jørgensen Ben Hur.                            
Henri Thorsen, 1893, Sparta, 15.1, 20-07-1924, Østerbro. Kilde: Dansk rekord 20-07-1924.                                                    
Peder Normann, 1955, Aalborg AK, 15.0, 18-09-1977,Østerbro. Kilde: Årbog 1977, side 96.                                           
Michael Jensen, 1962, AGF,15.1, 28-07-1984, Aarhus. Kilde: Årbog 1984, side 128.
Rene T. Nielsen, 1964, IF-Freja, Odense, 15.1, 25-08-1985, Esbjerg. Kilde: Årbog1985 side126.

Rettelser/ændringer 10-kamp:
Finn Sønderlund, 1929, Sparta, 6202, 18-06-1961, Frederiksberg. (11.1-6.22-11.19-1.70-51.6-16.0-33.82-3.30-42.67-4.23.8) Kilde: Masterranglisten.
Flemming Westh, 1934, Ben Hur, 6039, 18-06-1961, Frederiksberg. (11.2-6.90-11.65-1.73-52.1-16.0-31.69-3.10-46.07-5.10.6) Kilde: Sven Jørgensen Ben Hur.
Kent Johansen, 1964, Kolding KFUM, 6844, 19-07-1981, Aarhus. (11.6-6.51-10.55.1.90-50.9-16.7-33.08-4.30-62.51-4.17.7) Kilde: Årbog 81
Tom Rasmussen, 1948, Randers Freja, 6143, 10-10-1966, Randers. Ændring: Thor ændres til Tom

Vh Jens Pedersen

**Comment by jfraende** [comment]
Kære Jens

Tak det er modtaget - jeg kigger på korrektionerne, sammen med de andre 
du har sendt, når jeg får tid.

Vi er i fuld gang med stævnesæsonen, så tiden er desværre sparsom, men 
fortsæt endelig det gode arbejde.


-- 
Mvh.
Jesper Frænde
Statletik


Den 28-05-2017 kl. 12:49 skrev Sebastian Skejø:
