### ISSUE TITLE
Stedangivelse mangler på ranglister

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#42]

**Comment by sebastianskejoe** [comment]
@jfraende Problemet her er at stævner i v2 har lokationen gemt som et separat felt i databasen. Det er dog lidt svært at migrere, med mindre der er et bestemt mønster i hvordan stævnerne er navngivet. Gælder det altid at:
- Sidste ord i titlen er bynavn for danske stævner
- Hvis sidste ord består udelukkende af store bogstaver, skal hele navnet registreres som lokation (hvad er i så fald stævnenavnet?)

**Comment by jfraende** [comment]
JA - Med få undtagelser pga. fejlindtastning

Der er tradition for at angive udenlandske stævner med by, Landekode - sådan er de fleste også oprettet, men igen kan der være untagelser. Jeg er selv begyndt at angive hvis det er et mesterskab - fx http://old.statletik.dk/event.php?id=4220
