### ISSUE TITLE
forsvundne rekorder 

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#427]
Submitter: pernille kondrup
Email: pernillemkondrup@gmail.com
Hej 
Der står forkert registret udendørs rekord for pige 12 under 1000 m samt 600 m rekorden er
helt væk!!
Emma Kiplagat Kondrup 2004 har og var tidligere registreret i Jeres system som rekordindehaver
på 1000 m med 3.05.73 fra 2016 sat hendes 600 m rekord som 12 årig på 1.40.29 er også væk?

Er der en forklaring på dette?

Med venlig hilsen

Pernille Kondrup

**Comment by jfraende** [comment]
Hej Pernille

Rekorderne fremgår af denne side - 
http://statletik.dk/index.php/Records/index/female/outdoor/youth


-- 
Mvh.
Jesper Frænde
Statletik

Den 03-06-2017 kl. 19:53 skrev Sebastian Skejø:
