### ISSUE TITLE
fejl i konkurence på færøerne 14/6-17

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#431]
Submitter: regin thomsen
Email: optikarin@gmail.com
ang. http://statletik.dk/index.php/Meets/index/5254
nogle små rettelser, for en ordens skyld:

Konkurencen var ikke i Tórshavn, men på Svangaskarð (Toftir)
Ingi Johannesen (2000m) er ikke kvinde, han havde faktisk en statletik profil i forvejen, nu har HAN to.
Sólveig kastede faktisk med en 250g bold.
Hans Sivertsen løb en 300m også, den er ikke registreret ser det ud til.

**Comment by jfraende** [comment]
Tak - det er rettet.

Bold 250g er ikke den officielle vægt for piger. Det er ikke muligt at 
registrere på Statletik

-- 
Mvh.
Jesper Frænde
Statletik


Den 16-06-2017 kl. 21:32 skrev Sebastian Skejø:
