### ISSUE TITLE
Luis Maillet mangler resultat på D13 - 400 fra Hvidovre / Copenhagen Open

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#432]
Submitter: Eric Maillet
Email: ericmaillet@gmail.com
Hej, jeg kan se at de andre løb 80, 200 og 600 er overført, men ikke 400 ??? Er det en fejl?

**Comment by jfraende** [comment]
Ja, det var en fejl. De er med nu.

-- 
Mvh.
Jesper Frænde
Statletik


Den 18-06-2017 kl. 09:25 skrev Sebastian Skejø:
