### ISSUE TITLE
800 mangler fra Østmesterskaberne sidste weekend på Østerbro stadion 

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#435]
Submitter: Jesper Lützen
Email: jelut@live.dk
I hvert fald mangler 800 m piger 14-15 år

Og så har I stavet østmesterskaberne forkert...

Hilsen Jesper Lützen

**Comment by jfraende** [comment]
Stævnet er under indlægning, så du må have lidt tålmodighed :-)

-- 
Mvh.
Jesper Frænde
Statletik

Den 22-06-2017 kl. 21:30 skrev Sebastian Skejø:
