### ISSUE TITLE
Oversize-resultater blandes med almindelige

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#44]
Hvor for eksempel?

**Comment by jfraende** [comment]
Fx http://statletik.dk/index.php/Rankings/index/200m/0/m/indoor/2015/12/12/0/1/1/100/0

I det gamle Statletik er oversize en selvstændig disciplin på alle løb fra 200meter og opad - det skal vi have styr på. Kan man lave det som ved længdespring (option oversize) og eller en tjekbox hvor man kan inkludere oversize på sin rangliste - de er nemlig gyldige til DMU inde.

**Comment by sebastianskejoe** [comment]
Er rettet nu, men kræver en ny databasemigrering. Ændringen slår senest igennem i morgen.
