### ISSUE TITLE
Ukorrekt 400 m tid (?)

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#442]
Submitter: Ole Munch
Email: olbib2010@hotmail.com
Kære Statletik.

Ved Masters i Greve den 24.6.17 blev jeg kontaktet af en ældre, venlig herre, som ønskede at få oplyst min fødselsdato. Den fik han naturligvis, da hans ærinde var at opbygge en korrekt veteran-statistik.

Mit ærinde er at gøre ham opmærksom på, at den tid, som han formentlig har registreret mig for er en 400 m på 72,88 sek. Denne tid er imidlertid blot en træningstid på asfat, som jeg har opnået i mit lokalområede (vi har intet stadion), den er med selvstart, håndstoppet o.s.v.

Hvis jeg skal registreres for en reel 400 m tid, må det blive fra stævnet, lørdag den 24.6.17, hvor jeg bliver nr. 4 i +60 på 400 m i tiden 76,43.

Vil du/I venligst videresende meddelelsen til pågældende statistikker?

Venlig hilsen
Ole Munch - mobil 23 45 16 83

**Comment by jfraende** [comment]
Kære Ole

Du er registreret med 76,43 på Statletik - 
http://statletik.dk/index.php/Profile/index/7770

Statletik er den officielle statistik i Danmark og her registreres kun 
resultater fra godkendte stævner.

Jeg ved ikke hvem du har talt med, men det kunne være Claus Børsen som 
er CC denne mail.


-- 
Mvh.
Jesper Frænde
Statletik

Den 28-06-2017 kl. 13:37 skrev Sebastian Skejø:

**Comment by jfraende** [comment]
Hej Ole og Jesper!

Det er rigtigt, at jeg i lighed med adskillige andre masters udbad mig
Ole Munchs fødselsdag ved DM masters den 24. juni i Greve. Hans 400 m-tid
ved stævnet (76,43 sek.) blev registreret korrekt, men er desværre ikke
god nok til optagelse i min top50-liste for masters i gr. M60
(minimumskravet er pt. 73,01 sek.). Den omtalte tid på 72,88 er ikke
nogen, jeg kender til, og den figurerer heller ikke i top50.
Jeg håber, at du senere bliver i stand til at opnå en tid, der
kvalificerer til optagelse i ranglisten - eller måske på en anden
distance! Som tilfældet er ved flere andre atleter, vil jeg gemme dine
fødselsdata til evt. senere brug, og de vil udelukkende blive brugt i
top50-ranglisterne.

hilsen med tak for hjælpen
Claus Børsen
staistikfører for DAFs master-komite


----- Original meddelelse -----

**Comment by jfraende** [comment]
Hej Claus.


Det er bare så fint. Jeg beundrer meget din/jeres indsats på dette felt.


Venlig hilsen

Ole Munch

________________________________
Fra: Claus B�rsen <cboersen@pc.dk>
Sendt: 28. juni 2017 21:06:48
Til: Jesper Frænde
Cc: reply@reply.github.com; olbib2010@hotmail.com
Emne: Re: [sebastianskejoe/STatletik] Ukorrekt 400 m tid (?) (#442)

Hej Ole og Jesper!

Det er rigtigt, at jeg i lighed med adskillige andre masters udbad mig Ole Munchs fødselsdag ved DM masters den 24. juni i Greve. Hans 400 m-tid ved stævnet (76,43 sek.) blev registreret korrekt, men er desværre ikke god nok til optagelse i min top50-liste for masters i gr. M60 (minimumskravet er pt. 73,01 sek.). Den omtalte tid på 72,88 er ikke nogen, jeg kender til, og den figurerer heller ikke i top50.
        Jeg håber, at du senere bliver i stand til at opnå en tid, der kvalificerer til optagelse i ranglisten - eller måske på en anden distance! Som tilfældet er ved flere andre atleter, vil jeg gemme dine fødselsdata til evt. senere brug, og de vil udelukkende blive brugt i top50-ranglisterne.

hilsen med tak for hjælpen
Claus Børsen
staistikfører for DAFs master-komite


----- Original meddelelse -----
Fra: Jesper Frænde <jesper@jega.dk>
Til: reply@reply.github.com, olbib2010@hotmail.com, 'Claus Børsen' <cboersen@pc.dk>
Dato: Ons, 28. jun 2017 13:43
Emne: Re: [sebastianskejoe/STatletik] Ukorrekt 400 m tid (?) (#442)


Kære Ole

Du er registreret med 76,43 på Statletik - http://statletik.dk/index.php/Profile/index/7770

Statletik er den officielle statistik i Danmark og her registreres kun resultater fra godkendte stævner.

Jeg ved ikke hvem du har talt med, men det kunne være Claus Børsen som er CC denne mail.

--
Mvh.
Jesper Frænde
Statletik


Den 28-06-2017 kl. 13:37 skrev Sebastian Skejø:

Submitter: Ole Munch
Email: olbib2010@hotmail.com<mailto:olbib2010@hotmail.com>
Kære Statletik.

Ved Masters i Greve den 24.6.17 blev jeg kontaktet af en ældre, venlig herre, som ønskede at få oplyst min fødselsdato. Den fik han naturligvis, da hans ærinde var at opbygge en korrekt veteran-statistik.

Mit ærinde er at gøre ham opmærksom på, at den tid, som han formentlig har registreret mig for er en 400 m på 72,88 sek. Denne tid er imidlertid blot en træningstid på asfat, som jeg har opnået i mit lokalområede (vi har intet stadion), den er med selvstart, håndstoppet o.s.v.

Hvis jeg skal registreres for en reel 400 m tid, må det blive fra stævnet, lørdag den 24.6.17, hvor jeg bliver nr. 4 i +60 på 400 m i tiden 76,43.

Vil du/I venligst videresende meddelelsen til pågældende statistikker?

Venlig hilsen
Ole Munch - mobil 23 45 16 83
