### ISSUE TITLE
DT 1. Div. indled. øst damer Ballerup 21.06. 2017

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#448]
Submitter: Jesper Lützen 
Email: jelut@live.dk
Hejsa

Så vidt jeg kan se mangler dette stævne, i hvert fald kan jeg ikke finde Majken Lützen Ballerup AK og hendes 400 m på lige under et minut.

Hilsen Jesper Lützen

**Comment by jfraende** [comment]
Hej Jesper

Det er korrekt - men Ballerup har ikke afleveret resultatlisten i et 
format der kan lægges ind på Statletik. Så det er de stævneansvarlige 
derude du skal have fat i.

Før det sker har vi ikke mulighed (tid) til at lægge dem ind.


-- 
Mvh.
Jesper Frænde
Statletik

Den 03-07-2017 kl. 12:35 skrev Sebastian Skejø:
