### ISSUE TITLE
Ekstern klubstatistik på Statletik

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#72]
Submitter: Buster Nielsen
Email: buster.aadahl@gmail.com
Hej

Først og fremmest tillykke med den fine opdatering af statletik. I har sikkert stadig travlt med de sidste par ting, men vil alligevel komme med en lille forespørgsel.

Her i Odense Atletik har vi en database med 1000-vis af resultater fra adskillige årtier. Det kunne selvfølgelig være rart at få 'alt' overført, men hvordan det lige teknisk er muligt ved jeg ikke. Imidlertid kunne det være dejligt at få vores top ti lister overført. Hvilket format kunne det eventuelt indtastes i, så det kan blive lagt på statletik?

Listerne ser således ud: http://statistik.ogf.dk.web4.comasys.dk/viewStats.php?newAction=vaelg_disciplin&p_id=917&resultater_disciplin=5

Med venlig hilsen
Buster Nielsen

**Comment by jfraende** [comment]
besvaret/JF
