### ISSUE TITLE
Ikke godkendt vind på ranglister ved to ens resultater 

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#74]
Submitter: Marianne Benfeldt
Email: marianne.benfeldt@hotmail.com
Hej.
Fint arbejde med alt det data!!! 

Tror der er en bug! Hvis en atlet har samme resultat I godkendt vind og ikke godkendt vind,  lægges det ikke godkendte resultat på ranglisterne.
Caroline Benfeldt Sørensen har årets bedste 80m tid for piger 13 år. Tiden er 10,61 I vind 1,3. Hun løber dog samme tid ved samme stævne lidt senere. Her er vinden 2,7. Begge resultater er på hendes profil, men der føres forkert på ranglisterne. Lidt synd for hende, når Hun nu har årets bedste! Denne bug går igen...Alberte Lodahl I længdespring. 2 lige lange spring, men det med ikke godkendt vind føres over til ranglisterne. Det optræder sandsynligvis som en bug for alle atleter med samme resultat I godkendt og ikke godkendt vind.

Og I flere længdespring er ingen vind, istedet er datoen skubbet I kolonnen med vind.

Et par forslag...måske der kunne komme overskrifter på ranglisterne. Piger 13 år, 2015, og måske man kan vælge en disciplinkategori, der hedder alle, så man hurtigt kan tage en hel årgang ud I alle discipliner?

Keep up the good work!
Marianne Benfeldt

**Comment by jfraende** [comment]
Marianne besvaret

I øvrigt gode forslag hun har.

**Comment by sebastianskejoe** [comment]
Fejlene er rettet nu.

Ja, enig med forslagene. Den ene er vist oprettet som issue, den anden kan blive det med det samme.
