### ISSUE TITLE
Hvordan ser man at atleter har resultater fra flere klubber?

### ISSUE THREAD

**Issue by jfraende** [sebastianskejoe/STatletik#81]
Se fx http://statletik.dk/index.php/Profile/index/2749 som har de rekorder fra Sparta og mange gode resultater, men som i de senere år stillede op for Kolding KFUM

**Comment by sebastianskejoe** [comment]
Tilføjet klubnavn til resultater (ikke SB og PR).

**Comment by jfraende** [comment]
Men se lige på Robert igen - hans halvmarathon resultat står nu opført som sparta - her stillede han op for Kolding - se også hans gamle profil - http://old.statletik.dk/profil.php?year=2008&id=5453&sex=m

**Comment by sebastianskejoe** [comment]
På den gamle side står resultatet også opført som et Sparta-resultat, så derfor kommer det også i v2 som et sparta-resultat.

**Comment by jfraende** [comment]
Du har ret!
