### ISSUE TITLE
Kvinder 20 km er blevet registreret som 25 km i v2

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#89]
Submitter: aino slej
Email: aino@slej.dk
Hej. Flot nyt udseende. Fejl fundet: gamle tider, det var ikke 25 km men 20 km vi løb i firserne. Ny profil: min datters hækkeløb mangler både korte og lange. Vh Aino Slej

**Comment by jfraende** [comment]
Hej Aino

Tak for mail og rosen!

Det er helt klart en migreringsfejl til den nye database - resultatet er 
korrekt registreret som 20 km. Det er noteret til programmøren, og 
bliver rettet, så snart vi når til den på listen.

Jeg er lidt i tvivl om hvad der skulle være galt på din datters profil - 
umiddelbart ser det ud til alle resultater er kommet med. Kan du være 
mere konkret, gerne med link, hvor fejlen er?

## 

Mvh.
Jesper Frænde
Statletik

Den 26-11-2015 kl. 23:45 skrev Sebastian Skejø:

**Comment by sebastianskejoe** [comment]
Rettes ved næste migrering.
