### ISSUE TITLE
migrering af mesterskaber

### ISSUE THREAD

**Issue by sebastianskejoe** [sebastianskejoe/STatletik#99]
Submitter: Ole Mark Helwigh
Email: ole.mark@helwigh.dk
Hej Statletik

Der er fejl i Anna Mark Helwigh's  data om Mesterskaber (se neden for). Anna er bla. angivet til at ha' løbe som en "Dreng" - og så mangler der mange af hendes mesterskabsplaceringer. Jeg tror I havde styr på Annas mesterskabsplaceringer i den tidligere version af Statletik - så vil I selv hente dem der ? Eller skal jeg lige opsummere ? Som jeg husker Guld placeringerne så er de:  

DMU
DM Ungdom, ?? - P15 2015 800 m #1 
DM Ungdom, ?? - P15 2015 1500 m #1 

DM Ungdom, Østerbro - P15 2014 3000 m #1 
DM Ungdom, Østerbro - P15 2014 1500 m #1 

DMU-inde
DMU-inde, Skive - P15 2015 1500 m #1 
DMU-inde, Skive - P15 2015 3000 m #1

Hold guld: DM Senior 2015; Ungdom: DTU 2014; 2015

Mange hilsener
Ole

Den nuværende version af Stateltik siger:

DMU
DM Ungdom, Østerbro - D15 2014 3000 m #1 
DM Ungdom, Østerbro - D15 2014 1500 m #1 

DMU-inde
DMU-inde, Skive - D15 2014 3000 m #2

**Comment by jfraende** [comment]
Hej Ole

Der er ligenu en migreringsfejl på mesterskabsregistreringerne fra det 
gamle til det nye Statletik.
Vi arbejder selvfølgelig på, at der ikke bliver tabt nogle data. Men jeg 
kan ikke lige sige dig hvornår der bliver kigget på denne fejl.

Men vi arbejder på at alle fejl er fikset efter indesæsonen.

## 

Mvh.
Jesper Frænde
Statletik

Den 10-12-2015 kl. 12:58 skrev Sebastian Skejø:

**Comment by sebastianskejoe** [comment]
Er løst (i hvert fald på de personer jeg har tjekket - kan tåle et ekstra tjek).

**Comment by jfraende** [comment]
Jeg synes resultatet fra mesterskabet også bør vises - er det ikke muligt?

**Comment by jfraende** [comment]
Det ser ud til at mesterskaberne er forsvundet igen?

**Comment by sebastianskejoe** [comment]
Rettet igen - endnu en gang migreringen, der er død midt i forløbet.
